version: "3.8"

services:
  chatbot-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot-web

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chatbot-web.rule=Host(`chatbot.barron.agency`)"
      - "traefik.http.routers.chatbot-web.entrypoints=web"
      - "traefik.http.services.chatbot-web.loadbalancer.server.port=3000"
      - "traefik.http.routers.chatbot-web-secure.rule=Host(`chatbot.barron.agency`)"
      - "traefik.http.routers.chatbot-web-secure.entrypoints=websecure"
      - "traefik.http.routers.chatbot-web-secure.tls=true"

    networks:
      - proxy

networks:
  proxy:
    external: false
    name: proxy
