version: "3.8"

services:
  chatbotweb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbotweb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chatbotweb.rule=Host(`cryptotrack.barron.agency`)"
      - "traefik.http.routers.chatbotweb.entrypoints=web"
      - "traefik.http.services.chatbotweb.loadbalancer.server.port=3000"
      - "traefik.http.routers.chatbotweb-secure.rule=Host(`cryptotrack.barron.agency`)"
      - "traefik.http.routers.chatbotweb-secure.entrypoints=websecure"
      - "traefik.http.routers.chatbotweb-secure.tls=true"
    networks:
      - webnet

networks:
  webnet:
