version: "3.8"

services:
  chatbot-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot-web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chatbot-web.rule=Host(`cryptotrack.barron.agency`)"
      - "traefik.http.routers.chatbot-web.entrypoints=websecure"
      - "traefik.http.routers.chatbot-web.tls.certresolver=letsencrypt"
      - "traefik.http.services.chatbot-web.loadbalancer.server.port=3000"
    networks:
      - proxy

networks:
  proxy:
    external: true
    name: proxy
