name: Deploy to Server

on:
  push:
    branches:
      - master # oder der Branch, den du verwenden möchtest

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update application on server
        run: |
          cd repository/chatbotweb/
          git pull origin main
          docker-compose down
          docker-compose up -d --build
