name: Docker Prod

on:
  workflow_dispatch:
  push:
    branches: [master]
jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Create env file (ROOT)

      - name: Docker run
        run: docker compose up -d --force-recreate --build
