name: Self-hosted Runner Workflow

on:
  push:
    branches:
      - main  # Replace with your branch name
  pull_request:
    branches:
      - main  # Replace with your branch name

jobs:
  build:
    runs-on: self-hosted  # Specifies to use a self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Add more steps as needed for your specific build/test/deploy process
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      # Example of deploying to a server
      - name: Deploy
        run: |
          echo add other actions to build,
          echo test, and deploy your projekt,.

